/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MyCoursesRouteImport } from './routes/my-courses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CertificateValidationRouteImport } from './routes/certificate-validation'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as QuizQuizIdRouteImport } from './routes/quiz.$quizId'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as CourseSlugRouteImport } from './routes/course.$slug'
import { Route as CourseForumCourseIdRouteImport } from './routes/course-forum.$courseId'
import { Route as AssignmentAssignmentIdRouteImport } from './routes/assignment.$assignmentId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCoursesRoute = MyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateValidationRoute = CertificateValidationRouteImport.update({
  id: '/certificate-validation',
  path: '/certificate-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseForumCourseIdRoute = CourseForumCourseIdRouteImport.update({
  id: '/course-forum/$courseId',
  path: '/course-forum/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentAssignmentIdRoute = AssignmentAssignmentIdRouteImport.update({
  id: '/assignment/$assignmentId',
  path: '/assignment/$assignmentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/certificate-validation': typeof CertificateValidationRoute
  '/certificates': typeof CertificatesRoute
  '/courses': typeof CoursesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructors': typeof InstructorsRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assignment/$assignmentId': typeof AssignmentAssignmentIdRoute
  '/course-forum/$courseId': typeof CourseForumCourseIdRoute
  '/course/$slug': typeof CourseSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/certificate-validation': typeof CertificateValidationRoute
  '/certificates': typeof CertificatesRoute
  '/courses': typeof CoursesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructors': typeof InstructorsRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assignment/$assignmentId': typeof AssignmentAssignmentIdRoute
  '/course-forum/$courseId': typeof CourseForumCourseIdRoute
  '/course/$slug': typeof CourseSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/certificate-validation': typeof CertificateValidationRoute
  '/certificates': typeof CertificatesRoute
  '/courses': typeof CoursesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructors': typeof InstructorsRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assignment/$assignmentId': typeof AssignmentAssignmentIdRoute
  '/course-forum/$courseId': typeof CourseForumCourseIdRoute
  '/course/$slug': typeof CourseSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/certificate-validation'
    | '/certificates'
    | '/courses'
    | '/forgot-password'
    | '/instructors'
    | '/login'
    | '/my-courses'
    | '/orders'
    | '/profile'
    | '/purchases'
    | '/register'
    | '/reset-password'
    | '/assignment/$assignmentId'
    | '/course-forum/$courseId'
    | '/course/$slug'
    | '/learn/$slug'
    | '/payment/callback'
    | '/quiz/$quizId'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/certificate-validation'
    | '/certificates'
    | '/courses'
    | '/forgot-password'
    | '/instructors'
    | '/login'
    | '/my-courses'
    | '/orders'
    | '/profile'
    | '/purchases'
    | '/register'
    | '/reset-password'
    | '/assignment/$assignmentId'
    | '/course-forum/$courseId'
    | '/course/$slug'
    | '/learn/$slug'
    | '/payment/callback'
    | '/quiz/$quizId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/certificate-validation'
    | '/certificates'
    | '/courses'
    | '/forgot-password'
    | '/instructors'
    | '/login'
    | '/my-courses'
    | '/orders'
    | '/profile'
    | '/purchases'
    | '/register'
    | '/reset-password'
    | '/assignment/$assignmentId'
    | '/course-forum/$courseId'
    | '/course/$slug'
    | '/learn/$slug'
    | '/payment/callback'
    | '/quiz/$quizId'
    | '/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CertificateValidationRoute: typeof CertificateValidationRoute
  CertificatesRoute: typeof CertificatesRoute
  CoursesRoute: typeof CoursesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InstructorsRoute: typeof InstructorsRoute
  LoginRoute: typeof LoginRoute
  MyCoursesRoute: typeof MyCoursesRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  PurchasesRoute: typeof PurchasesRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AssignmentAssignmentIdRoute: typeof AssignmentAssignmentIdRoute
  CourseForumCourseIdRoute: typeof CourseForumCourseIdRoute
  CourseSlugRoute: typeof CourseSlugRoute
  LearnSlugRoute: typeof LearnSlugRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  QuizQuizIdRoute: typeof QuizQuizIdRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-courses': {
      id: '/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof MyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate-validation': {
      id: '/certificate-validation'
      path: '/certificate-validation'
      fullPath: '/certificate-validation'
      preLoaderRoute: typeof CertificateValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$slug': {
      id: '/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-forum/$courseId': {
      id: '/course-forum/$courseId'
      path: '/course-forum/$courseId'
      fullPath: '/course-forum/$courseId'
      preLoaderRoute: typeof CourseForumCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignment/$assignmentId': {
      id: '/assignment/$assignmentId'
      path: '/assignment/$assignmentId'
      fullPath: '/assignment/$assignmentId'
      preLoaderRoute: typeof AssignmentAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CertificateValidationRoute: CertificateValidationRoute,
  CertificatesRoute: CertificatesRoute,
  CoursesRoute: CoursesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InstructorsRoute: InstructorsRoute,
  LoginRoute: LoginRoute,
  MyCoursesRoute: MyCoursesRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  PurchasesRoute: PurchasesRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AssignmentAssignmentIdRoute: AssignmentAssignmentIdRoute,
  CourseForumCourseIdRoute: CourseForumCourseIdRoute,
  CourseSlugRoute: CourseSlugRoute,
  LearnSlugRoute: LearnSlugRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  QuizQuizIdRoute: QuizQuizIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
