/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register/step/1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Step One */
        post: operations["register_step_one_api_v1_auth_register_step_1_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/step/2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Step Two */
        post: operations["register_step_two_api_v1_auth_register_step_2_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/step/3": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Step Three */
        post: operations["register_step_three_api_v1_auth_register_step_3_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verification */
        post: operations["verification_api_v1_auth_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forget-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forget Password */
        post: operations["forget_password_api_v1_auth_forget_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_auth_reset_password__token__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google Callback */
        post: operations["google_callback_api_v1_auth_google_callback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/facebook/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Facebook Callback */
        post: operations["facebook_callback_api_v1_auth_facebook_callback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_api_v1_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_api_v1_courses__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_v1_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trend-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trend Categories */
        get: operations["list_trend_categories_api_v1_trend_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/featured-courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Featured Courses */
        get: operations["featured_courses_api_v1_featured_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/profile-setting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_panel_profile_setting_get"];
        /** Update Profile */
        put: operations["update_profile_api_v1_panel_profile_setting_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/profile-setting/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Password */
        put: operations["update_password_api_v1_panel_profile_setting_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/profile-setting/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Images */
        post: operations["update_images_api_v1_panel_profile_setting_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthToken
         * @description Token plus the authenticated user id (returned after register step 3).
         */
        AuthToken: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** User Id */
            user_id: number;
        };
        /** Body_update_images_api_v1_panel_profile_setting_images_post */
        Body_update_images_api_v1_panel_profile_setting_images_post: {
            /** Profile Image */
            profile_image?: string | null;
            /** Identity Scan */
            identity_scan?: string | null;
            /** Certificate */
            certificate?: string | null;
        };
        /** CategoryList */
        CategoryList: {
            /** Count */
            count: number;
            /** Categories */
            categories: components["schemas"]["CategoryRead"][];
        };
        /** CategoryRead */
        CategoryRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Color */
            color?: string | null;
            /** Icon */
            icon?: string | null;
            /**
             * Sub Categories
             * @default []
             */
            sub_categories: components["schemas"]["SubCategoryRead"][];
            /**
             * Webinars Count
             * @default 0
             */
            webinars_count: number;
        };
        /**
         * CourseDetail
         * @description Legacy `Webinar::details` = brief + the keys below.
         */
        CourseDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            type: components["schemas"]["CourseType"];
            status: components["schemas"]["CourseStatus"];
            /** Label */
            label?: string | null;
            /** Image */
            image?: string | null;
            /** Image Cover */
            image_cover?: string | null;
            /** Price */
            price: number;
            /** Price String */
            price_string?: string | null;
            /** Best Ticket Price */
            best_ticket_price?: number | null;
            /**
             * Discount Percent
             * @default 0
             */
            discount_percent: number;
            /** Duration */
            duration?: number | null;
            /** Access Days */
            access_days?: number | null;
            /** Capacity */
            capacity?: number | null;
            /** Points */
            points?: number | null;
            /** Start Date */
            start_date?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            teacher?: components["schemas"]["CourseTeacher"] | null;
            /** Category */
            category?: string | null;
            /** Category Id */
            category_id?: number | null;
            /**
             * Students Count
             * @default 0
             */
            students_count: number;
            /**
             * Rate
             * @default 0
             */
            rate: number;
            /**
             * Reviews Count
             * @default 0
             */
            reviews_count: number;
            /**
             * Is Favorite
             * @default false
             */
            is_favorite: boolean;
            /**
             * Is Private
             * @default false
             */
            is_private: boolean;
            /**
             * Forum
             * @default false
             */
            forum: boolean;
            /**
             * Badges
             * @default []
             */
            badges: {
                [key: string]: unknown;
            }[];
            /**
             * Auth
             * @default false
             */
            auth: boolean;
            /**
             * Auth Has Bought
             * @default false
             */
            auth_has_bought: boolean;
            /**
             * Can View
             * @default true
             */
            can_view: boolean;
            /** Can View Error */
            can_view_error?: string[] | null;
            /** Description */
            description?: string | null;
            /** Seo Description */
            seo_description?: string | null;
            /** Video Demo */
            video_demo?: string | null;
            video_demo_source?: components["schemas"]["VideoDemoSource"] | null;
            /**
             * Support
             * @default false
             */
            support: boolean;
            /**
             * Subscribe
             * @default false
             */
            subscribe: boolean;
            /**
             * Downloadable
             * @default false
             */
            downloadable: boolean;
            /**
             * Certificate
             * @default false
             */
            certificate: boolean;
            /**
             * Can Add To Cart
             * @default false
             */
            can_add_to_cart: boolean;
            /**
             * Can Buy With Points
             * @default false
             */
            can_buy_with_points: boolean;
            /**
             * Tax
             * @default 0
             */
            tax: number;
            /**
             * Price With Discount
             * @default 0
             */
            price_with_discount: number;
            /**
             * @default {
             *       "content_quality": 0,
             *       "instructor_skills": 0,
             *       "purchase_worth": 0,
             *       "support_quality": 0
             *     }
             */
            rate_type: components["schemas"]["CourseRateType"];
            /**
             * Prerequisites
             * @default []
             */
            prerequisites: {
                [key: string]: unknown;
            }[];
            /**
             * Faqs
             * @default []
             */
            faqs: {
                [key: string]: unknown;
            }[];
            /**
             * Tags
             * @default []
             */
            tags: {
                [key: string]: unknown;
            }[];
            /**
             * Comments
             * @default []
             */
            comments: {
                [key: string]: unknown;
            }[];
            /**
             * Reviews
             * @default []
             */
            reviews: {
                [key: string]: unknown;
            }[];
            /**
             * Chapters
             * @default []
             */
            chapters: {
                [key: string]: unknown;
            }[];
            /**
             * Sessions Count
             * @default 0
             */
            sessions_count: number;
            /**
             * Files Count
             * @default 0
             */
            files_count: number;
            /**
             * Text Lessons Count
             * @default 0
             */
            text_lessons_count: number;
            /**
             * Quizzes
             * @default []
             */
            quizzes: {
                [key: string]: unknown;
            }[];
            /**
             * Quizzes Count
             * @default 0
             */
            quizzes_count: number;
            /**
             * Certificate Quizzes
             * @default []
             */
            certificate_quizzes: {
                [key: string]: unknown;
            }[];
            /**
             * Tickets
             * @default []
             */
            tickets: {
                [key: string]: unknown;
            }[];
        };
        /** CourseRateType */
        CourseRateType: {
            /**
             * Content Quality
             * @default 0
             */
            content_quality: number;
            /**
             * Instructor Skills
             * @default 0
             */
            instructor_skills: number;
            /**
             * Purchase Worth
             * @default 0
             */
            purchase_worth: number;
            /**
             * Support Quality
             * @default 0
             */
            support_quality: number;
        };
        /**
         * CourseRead
         * @description Legacy `Webinar::brief` — list cards and the base of detail.
         */
        CourseRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            type: components["schemas"]["CourseType"];
            status: components["schemas"]["CourseStatus"];
            /** Label */
            label?: string | null;
            /** Image */
            image?: string | null;
            /** Image Cover */
            image_cover?: string | null;
            /** Price */
            price: number;
            /** Price String */
            price_string?: string | null;
            /** Best Ticket Price */
            best_ticket_price?: number | null;
            /**
             * Discount Percent
             * @default 0
             */
            discount_percent: number;
            /** Duration */
            duration?: number | null;
            /** Access Days */
            access_days?: number | null;
            /** Capacity */
            capacity?: number | null;
            /** Points */
            points?: number | null;
            /** Start Date */
            start_date?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            teacher?: components["schemas"]["CourseTeacher"] | null;
            /** Category */
            category?: string | null;
            /** Category Id */
            category_id?: number | null;
            /**
             * Students Count
             * @default 0
             */
            students_count: number;
            /**
             * Rate
             * @default 0
             */
            rate: number;
            /**
             * Reviews Count
             * @default 0
             */
            reviews_count: number;
            /**
             * Is Favorite
             * @default false
             */
            is_favorite: boolean;
            /**
             * Is Private
             * @default false
             */
            is_private: boolean;
            /**
             * Forum
             * @default false
             */
            forum: boolean;
            /**
             * Badges
             * @default []
             */
            badges: {
                [key: string]: unknown;
            }[];
            /**
             * Auth
             * @default false
             */
            auth: boolean;
            /**
             * Auth Has Bought
             * @default false
             */
            auth_has_bought: boolean;
            /**
             * Can View
             * @default true
             */
            can_view: boolean;
            /** Can View Error */
            can_view_error?: string[] | null;
        };
        /**
         * CourseStatus
         * @description Legacy `webinars.status` enum (parity — was draft/published/archived).
         * @enum {string}
         */
        CourseStatus: "active" | "pending" | "is_draft" | "inactive";
        /**
         * CourseTeacher
         * @description Subset of the legacy `teacher->brief` available in Phase 1.
         */
        CourseTeacher: {
            /** Id */
            id: number;
            /** Username */
            username?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** Role Name */
            role_name?: string | null;
            /** Avatar */
            avatar?: string | null;
            /** Bio */
            bio?: string | null;
            /** Headline */
            headline?: string | null;
            /**
             * Offline
             * @default false
             */
            offline: boolean;
        };
        /**
         * CourseType
         * @description Legacy `webinars.type` enum (webinar = live, course = self-paced).
         * @enum {string}
         */
        CourseType: "webinar" | "course" | "text_lesson";
        /**
         * ErrorResponse
         * @description Shape of FastAPI's default HTTPException body (`{"detail": "..."}`).
         *
         *     Declared on routes via `responses=` so the error contract is part of the
         *     OpenAPI schema and the generated frontend client types `error` honestly.
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /** Type */
            type?: string | null;
            /** Email */
            email?: string | null;
            /** Mobile */
            mobile?: string | null;
            /** Country Code */
            country_code?: string | null;
        };
        /** ForgotPasswordResult */
        ForgotPasswordResult: {
            /** Status */
            status: string;
            /** Token */
            token?: string | null;
            /** New Password */
            new_password?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImagesResult */
        ImagesResult: {
            /**
             * Status
             * @default updated
             */
            status: string;
            /** Avatar */
            avatar?: string | null;
            /** Identity Scan */
            identity_scan?: string | null;
            /** Certificate */
            certificate?: string | null;
        };
        /** LocationInput */
        LocationInput: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** User Id */
            user_id: number;
            /**
             * Profile Completion
             * @default []
             */
            profile_completion: string[];
        };
        /** LogoutResult */
        LogoutResult: {
            /**
             * Status
             * @default logout
             */
            status: string;
        };
        /**
         * MeetingType
         * @enum {string}
         */
        MeetingType: "all" | "in_person" | "online";
        /** OAuthCallback */
        OAuthCallback: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Id */
            id: string;
        };
        /** OAuthResult */
        OAuthResult: {
            /** Status */
            status: string;
            /** User Id */
            user_id: number;
            /** Already Registered */
            already_registered: boolean;
            /** Token */
            token?: string | null;
        };
        /** OrganizationsGroup */
        OrganizationsGroup: {
            /**
             * Organizations
             * @default []
             */
            organizations: components["schemas"]["UserBrief"][];
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /** PasswordUpdate */
        PasswordUpdate: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PasswordUpdateResult */
        PasswordUpdateResult: {
            /**
             * Status
             * @default updated
             */
            status: string;
            /** Token */
            token: string;
        };
        /** ProfileRead */
        ProfileRead: {
            /** Id */
            id: number;
            /** Email */
            email: string | null;
            /** Mobile */
            mobile: string | null;
            /** Full Name */
            full_name: string | null;
            /** Role Name */
            role_name: string;
            status: components["schemas"]["UserStatus"];
            /** Verified */
            verified: boolean;
            /** Avatar */
            avatar: string | null;
            /** Cover Img */
            cover_img: string | null;
            /** Bio */
            bio: string | null;
            /** Headline */
            headline: string | null;
            /** About */
            about: string | null;
            /** Address */
            address: string | null;
            /** Language */
            language: string | null;
            /** Timezone */
            timezone: string | null;
            /** Currency */
            currency: string | null;
            theme_color_mode: components["schemas"]["ThemeColorMode"] | null;
            /** Newsletter */
            newsletter: boolean;
            /** Public Message */
            public_message: boolean;
            /** Account Type */
            account_type: string | null;
            /** Iban */
            iban: string | null;
            /** Account Id */
            account_id: string | null;
            meeting_type: components["schemas"]["MeetingType"];
            /** Level Of Training */
            level_of_training: number | null;
            /** Country Id */
            country_id: number | null;
            /** Province Id */
            province_id: number | null;
            /** City Id */
            city_id: number | null;
            /** District Id */
            district_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Language */
            language?: string | null;
            /** Email */
            email?: string | null;
            /** Mobile */
            mobile?: string | null;
            /** Newsletter */
            newsletter?: boolean | null;
            /** Public Message */
            public_message?: boolean | null;
            /** Timezone */
            timezone?: string | null;
            /** Password */
            password?: string | null;
            /** About */
            about?: string | null;
            /** Bio */
            bio?: string | null;
            /** Address */
            address?: string | null;
            /** Account Type */
            account_type?: string | null;
            /** Iban */
            iban?: string | null;
            /** Account Id */
            account_id?: string | null;
            meeting_type?: components["schemas"]["MeetingType"] | null;
            /** Level Of Training */
            level_of_training?: string[] | null;
            location?: components["schemas"]["LocationInput"] | null;
            /** Country Id */
            country_id?: number | null;
            /** Province Id */
            province_id?: number | null;
            /** City Id */
            city_id?: number | null;
            /** District Id */
            district_id?: number | null;
        };
        /** RegisterStep1 */
        RegisterStep1: {
            /** Email */
            email?: string | null;
            /** Mobile */
            mobile?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Password */
            password: string;
            /** Password Confirmation */
            password_confirmation: string;
        };
        /** RegisterStep1Response */
        RegisterStep1Response: {
            /** Status */
            status: string;
            /** User Id */
            user_id: number;
            /** Code */
            code?: string | null;
        };
        /** RegisterStep2 */
        RegisterStep2: {
            /** User Id */
            user_id: number;
            /** Code */
            code: string;
        };
        /** RegisterStep3 */
        RegisterStep3: {
            /** User Id */
            user_id: number;
            /** Full Name */
            full_name: string;
            /** Referral Code */
            referral_code?: string | null;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Password Confirmation */
            password_confirmation: string;
        };
        /** ResetPasswordResult */
        ResetPasswordResult: {
            /** Status */
            status: string;
        };
        /**
         * SearchResults
         * @description Legacy SearchController shape (multi-entity global search).
         */
        SearchResults: {
            /**
             * @default {
             *       "webinars": [],
             *       "count": 0
             *     }
             */
            webinars: components["schemas"]["WebinarsGroup"];
            /**
             * @default {
             *       "users": [],
             *       "count": 0
             *     }
             */
            users: components["schemas"]["UsersGroup"];
            /**
             * @default {
             *       "teachers": [],
             *       "count": 0
             *     }
             */
            teachers: components["schemas"]["TeachersGroup"];
            /**
             * @default {
             *       "organizations": [],
             *       "count": 0
             *     }
             */
            organizations: components["schemas"]["OrganizationsGroup"];
        };
        /** SubCategoryRead */
        SubCategoryRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Icon */
            icon?: string | null;
            /**
             * Webinars Count
             * @default 0
             */
            webinars_count: number;
        };
        /** TeachersGroup */
        TeachersGroup: {
            /**
             * Teachers
             * @default []
             */
            teachers: components["schemas"]["UserBrief"][];
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /**
         * ThemeColorMode
         * @enum {string}
         */
        ThemeColorMode: "dark" | "light";
        /** TrendCategoryList */
        TrendCategoryList: {
            /** Count */
            count: number;
            /** Categories */
            categories: components["schemas"]["TrendCategoryRead"][];
        };
        /** TrendCategoryRead */
        TrendCategoryRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Color */
            color?: string | null;
            /** Icon */
            icon?: string | null;
        };
        /**
         * UserBrief
         * @description Public, minimal user card (legacy user->brief subset).
         */
        UserBrief: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string | null;
            /** Role Name */
            role_name: string;
            /** Avatar */
            avatar: string | null;
            /** Headline */
            headline: string | null;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /** Email */
            email: string | null;
            /** Mobile */
            mobile: string | null;
            /** Full Name */
            full_name: string | null;
            /** Role Name */
            role_name: string;
            status: components["schemas"]["UserStatus"];
            /** Verified */
            verified: boolean;
            /** Avatar */
            avatar: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "active" | "pending" | "inactive";
        /** UsersGroup */
        UsersGroup: {
            /**
             * Users
             * @default []
             */
            users: components["schemas"]["UserBrief"][];
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerificationConfirm */
        VerificationConfirm: {
            /** Username */
            username: string;
            /** Code */
            code: string;
            /** Referral Code */
            referral_code?: string | null;
        };
        /** VerificationResult */
        VerificationResult: {
            /**
             * Status
             * @default verified
             */
            status: string;
        };
        /**
         * VideoDemoSource
         * @enum {string}
         */
        VideoDemoSource: "upload" | "youtube" | "vimeo" | "external_link";
        /** WebinarsGroup */
        WebinarsGroup: {
            /**
             * Webinars
             * @default []
             */
            webinars: components["schemas"]["CourseRead"][];
            /**
             * Count
             * @default 0
             */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_step_one_api_v1_auth_register_step_1_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterStep1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterStep1Response"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    register_step_two_api_v1_auth_register_step_2_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterStep2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    register_step_three_api_v1_auth_register_step_3_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterStep3"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthToken"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verification_api_v1_auth_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResult"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    forget_password_api_v1_auth_forget_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgotPasswordResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password__token__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordResult"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    google_callback_api_v1_auth_google_callback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthCallback"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facebook_callback_api_v1_auth_facebook_callback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthCallback"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_courses_api_v1_courses_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description category id */
                cat?: number | null;
                free?: boolean | null;
                type?: components["schemas"]["CourseType"] | null;
                upcoming?: boolean | null;
                downloadable?: boolean | null;
                reward?: boolean | null;
                /** @description newest|oldest|expensive|cheapest */
                sort?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_api_v1_courses__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_v1_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryList"];
                };
            };
        };
    };
    list_trend_categories_api_v1_trend_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendCategoryList"];
                };
            };
        };
    };
    featured_courses_api_v1_featured_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseRead"][];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query?: {
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_panel_profile_setting_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_profile_api_v1_panel_profile_setting_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_password_api_v1_panel_profile_setting_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordUpdateResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_images_api_v1_panel_profile_setting_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_update_images_api_v1_panel_profile_setting_images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagesResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
